<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BooksSeeder extends Seeder
{
    /**
     * Buku hits populer Indonesia + koleksi klasik sastra dunia.
     */
    public function run(): void
    {
        DB::table('books')->insert([

            // ─── BUKU HITS POPULER (tampil di rak 3D beranda) ───

            [
                'isbn'           => '978-602-424-694-5',
                'title'          => 'Laut Bercerita',
                'author'         => 'Leila S. Chudori',
                'publisher'      => 'KPG (Kepustakaan Populer Gramedia)',
                'image'          => 'images/books/laut_real.jpg',
                'shelf_number'   => 'B2-010',
                'category'       => 'Fiction',
                'stock'          => 25,
                'is_featured'    => true,
                'description'    => 'Novel tentang perjuangan aktivis mahasiswa 1998 yang diculik dan kisah pencarian kebenaran oleh keluarganya. Karya Leila S. Chudori yang memenangkan S.E.A. Write Award dan menjadi novel paling berpengaruh bagi generasi muda.',
                'language'       => 'Indonesian',
                'published_date' => '2017-10-26',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-623-110-046-1',
                'title'          => 'Seporsi Mie Ayam Sebelum Mati',
                'author'         => 'Brian Khrisna',
                'publisher'      => 'Grasindo',
                'image'          => 'images/books/mieayam_front.jpg',
                'shelf_number'   => 'F6-010',
                'category'       => 'Self-Help',
                'stock'          => 30,
                'is_featured'    => true,
                'description'    => 'Kumpulan esai reflektif dan puitis karya Brian Khrisna tentang perjuangan menghadapi kesepian, kesehatan mental, rasa syukur, dan menikmati hal-hal kecil sebelum semuanya berlalu.',
                'language'       => 'Indonesian',
                'published_date' => '2024-01-15',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-602-412-518-9',
                'title'          => 'Filosofi Teras',
                'author'         => 'Henry Manampiring',
                'publisher'      => 'Penerbit Buku Kompas',
                'image'          => 'images/books/filosofi_cover.jpg',
                'shelf_number'   => 'F6-003',
                'category'       => 'Self-Help',
                'stock'          => 18,
                'is_featured'    => true,
                'description'    => 'Penerapan filsafat Stoisisme kuno Yunani-Romawi yang relevan untuk mengatasi kekhawatiran, overthinking, dan melatih ketenangan mental masa kini. Pemenang Book of the Year di Indonesia.',
                'language'       => 'Indonesian',
                'published_date' => '2018-11-26',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-979-168-333-3',
                'title'          => 'Madilog',
                'author'         => 'Tan Malaka',
                'publisher'      => 'Pusat Data Indikator',
                'image'          => 'images/books/madilog_real_g.jpg',
                'shelf_number'   => 'G7-001',
                'category'       => 'Philosophy',
                'stock'          => 12,
                'is_featured'    => true,
                'description'    => 'Singkatan dari Materialisme, Dialektika, dan Logika — karya monumental Tan Malaka tentang metode berpikir ilmiah dan kritis untuk membebaskan akal budi bangsa dari logika mistika.',
                'language'       => 'Indonesian',
                'published_date' => '1951-01-01',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-602-03-1258-3',
                'title'          => 'Cantik Itu Luka',
                'author'         => 'Eka Kurniawan',
                'publisher'      => 'Gramedia Pustaka Utama',
                'image'          => 'images/books/cantik_itu_luka.jpg',
                'shelf_number'   => 'B2-011',
                'category'       => 'Fiction',
                'stock'          => 22,
                'is_featured'    => true,
                'description'    => 'Novel epos realisme magis yang mengikuti empat generasi keluarga Dewi Ayu, seorang pelacur tercantik di kota Halimunda yang bangkit dari kuburnya setelah 21 tahun mati. Karya adiluhung Eka Kurniawan yang diakui dunia internasional.',
                'language'       => 'Indonesian',
                'published_date' => '2002-09-01',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-979-1227-78-0',
                'title'          => 'Perahu Kertas',
                'author'         => 'Dee Lestari',
                'publisher'      => 'Bentang Pustaka',
                'image'          => 'images/books/perahu_cover.jpg',
                'shelf_number'   => 'B2-012',
                'category'       => 'Fiction',
                'stock'          => 20,
                'is_featured'    => true,
                'description'    => 'Kisah cinta, mimpi, dan persahabatan antara Kugy, sang agen Neptunus yang bercita-cita menjadi juru dongeng, dan Keenan, pelukis berbakat. Karya ikonik Dee Lestari yang menjadi simbol generasi kreatif Indonesia.',
                'language'       => 'Indonesian',
                'published_date' => '2009-08-29',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-602-06-4932-0',
                'title'          => 'The Midnight Library',
                'author'         => 'Matt Haig',
                'publisher'      => 'Gramedia Pustaka Utama',
                'image'          => 'images/books/midnight_real_g.jpg',
                'shelf_number'   => 'A1-010',
                'category'       => 'Fiction',
                'stock'          => 17,
                'is_featured'    => true,
                'description'    => 'Novel fiksi filosofis tentang Nora Seed yang menemukan perpustakaan ajaib di antara hidup dan mati, di mana setiap buku membuka kemungkinan kehidupan yang belum pernah ia jalani. Pemenang Goodreads Choice Awards.',
                'language'       => 'Indonesian',
                'published_date' => '2020-08-13',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-602-291-411-2',
                'title'          => 'Sirkus Pohon',
                'author'         => 'Andrea Hirata',
                'publisher'      => 'Bentang Pustaka',
                'image'          => 'images/books/sirkus_front_flat.jpg',
                'shelf_number'   => 'B2-013',
                'category'       => 'Fiction',
                'stock'          => 14,
                'is_featured'    => true,
                'description'    => 'Novel penuh warna berlatar kampung Melayu Belitong tentang Hobri yang menjadi badut sirkus keliling demi memenangkan hati gadis pujaannya, di bawah naungan sebatang pohon filicium keramat.',
                'language'       => 'Indonesian',
                'published_date' => '2017-08-15',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-979-22-4861-6',
                'title'          => 'Negeri 5 Menara',
                'author'         => 'A. Fuadi',
                'publisher'      => 'Gramedia Pustaka Utama',
                'image'          => 'images/books/negeri5_real_g.jpg',
                'shelf_number'   => 'B2-014',
                'category'       => 'Fiction',
                'stock'          => 16,
                'is_featured'    => true,
                'description'    => 'Kisah inspiratif tentang Alif dan lima sahabatnya di Pondok Madani dengan mantra pengubah takdir "Man Jadda Wajada" yang memotivasi jutaan generasi muda Indonesia untuk meraih mimpi besar.',
                'language'       => 'Indonesian',
                'published_date' => '2009-07-01',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],

            // ─── KOLEKSI UMUM & KLASIK DUNIA ───

            [
                'isbn'           => '978-602-6940-14-8',
                'title'          => 'Dear Nathan',
                'author'         => 'Erisca Febriani',
                'publisher'      => 'Best Media',
                'image'          => 'images/books/dear_nathan_wiki.jpg',
                'shelf_number'   => 'G7-002',
                'category'       => 'Romance',
                'stock'          => 13,
                'is_featured'    => false,
                'description'    => 'Novel romance remaja tentang Salma dan Nathan yang viral dari Wattpad dan menjadi fenomena sastra anak muda Indonesia hingga sukses diadaptasi ke film layar lebar.',
                'language'       => 'Indonesian',
                'published_date' => '2016-03-01',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-0-7475-3269-9',
                'title'          => 'Harry Potter and the Philosopher\'s Stone',
                'author'         => 'J.K. Rowling',
                'publisher'      => 'Bloomsbury',
                'image'          => 'images/books/hp_cover.jpg',
                'shelf_number'   => 'A1-001',
                'category'       => 'Fantasy',
                'stock'          => 10,
                'is_featured'    => false,
                'description'    => 'Buku pertama seri petualangan fantasi legendaris Harry Potter yang mengisahkan perjalanannya menemukan jati diri sebagai penyihir di Sekolah Sihir Hogwarts.',
                'language'       => 'English',
                'published_date' => '1997-06-26',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-0-06-112008-4',
                'title'          => 'To Kill a Mockingbird',
                'author'         => 'Harper Lee',
                'publisher'      => 'J.B. Lippincott & Co.',
                'image'          => 'images/books/mockingbird_cover.jpg',
                'shelf_number'   => 'B2-002',
                'category'       => 'Fiction',
                'stock'          => 8,
                'is_featured'    => false,
                'description'    => 'Karya klasik sastra dunia pemenang Hadiah Pulitzer mengenai keadilan rasial, moralitas, dan kepolosan masa kanak-kanak di Alabama tahun 1930-an.',
                'language'       => 'English',
                'published_date' => '1960-07-11',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-0-451-52493-5',
                'title'          => '1984',
                'author'         => 'George Orwell',
                'publisher'      => 'Secker & Warburg',
                'image'          => 'images/books/orwell_cover.jpg',
                'shelf_number'   => 'C3-003',
                'category'       => 'Dystopian',
                'stock'          => 12,
                'is_featured'    => false,
                'description'    => 'Novel distopia peringatan karya George Orwell tentang masyarakat totaliter di bawah kekuasaan mutlak Big Brother, manipulasi kebenaran, dan pengawasan massal.',
                'language'       => 'English',
                'published_date' => '1949-06-08',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-0-7352-1129-2',
                'title'          => 'Atomic Habits',
                'author'         => 'James Clear',
                'publisher'      => 'Avery',
                'image'          => 'images/books/atomic_cover.jpg',
                'shelf_number'   => 'F6-001',
                'category'       => 'Self-Help',
                'stock'          => 20,
                'is_featured'    => false,
                'description'    => 'Panduan praktis terlaris dunia untuk membangun kebiasaan baik dan menghilangkan kebiasaan buruk melalui perubahan kecil 1% setiap hari yang memberikan dampak luar biasa.',
                'language'       => 'English',
                'published_date' => '2018-10-16',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-979-3062-79-2',
                'title'          => 'Laskar Pelangi',
                'author'         => 'Andrea Hirata',
                'publisher'      => 'Bentang Pustaka',
                'image'          => 'images/books/laskar_cover.jpg',
                'shelf_number'   => 'B2-005',
                'category'       => 'Fiction',
                'stock'          => 14,
                'is_featured'    => false,
                'description'    => 'Kisah perjuangan sepuluh anak di Belitong dalam mengejar pendidikan dan mimpi besar mereka di tengah keterbatasan. Novel terlaris sepanjang masa di Indonesia.',
                'language'       => 'Indonesian',
                'published_date' => '2005-09-01',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-0-261-10221-7',
                'title'          => 'The Hobbit',
                'author'         => 'J.R.R. Tolkien',
                'publisher'      => 'George Allen & Unwin',
                'image'          => 'images/books/hobbit_cover.jpg',
                'shelf_number'   => 'A1-002',
                'category'       => 'Fantasy',
                'stock'          => 7,
                'is_featured'    => false,
                'description'    => 'Petualangan fantasi klasik karya J.R.R. Tolkien tentang perjalanan Bilbo Baggins bersama para kurcaci untuk merebut kembali kerajaan Erebor dan harta karun dari naga Smaug.',
                'language'       => 'English',
                'published_date' => '1937-09-21',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
        ]);
    }
}