<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BooksSeeder extends Seeder
{
    /**
     * Buku hits Gen-Z Indonesia + koleksi klasik internasional.
     */
    public function run(): void
    {
        DB::table('books')->insert([

            // ─── BUKU HITS GEN-Z (tampil di rak 3D beranda) ───

            [
                'isbn'           => '978-602-060-494-0',
                'title'          => 'Laut Bercerita',
                'author'         => 'Leila S. Chudori',
                'publisher'      => 'KPG (Kepustakaan Populer Gramedia)',
                'image'          => 'images/books/laut_real.jpg',
                'shelf_number'   => 'B2-010',
                'category'       => 'Fiction',
                'stock'          => 25,
                'is_featured'    => true,
                'description'    => 'Novel tentang perjuangan aktivis mahasiswa 1998 yang diculik dan kisah pencarian kebenaran oleh keluarganya. Salah satu novel Indonesia paling berpengaruh bagi generasi muda.',
                'language'       => 'Indonesian',
                'published_date' => '2017-10-26',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-623-110-046-1',
                'title'          => 'Seporsi Mie Ayam Sebelum Mati',
                'author'         => 'Brian Khrisna',
                'publisher'      => 'Grasindo',
                'image'          => 'images/books/mieayam_front.jpg',
                'shelf_number'   => 'F6-010',
                'category'       => 'Self-Help',
                'stock'          => 30,
                'is_featured'    => true,
                'description'    => 'Kumpulan esai reflektif dan puitis tentang kehidupan, kematian, rasa syukur, dan menikmati hal-hal kecil sebelum semuanya berlalu. Buku paling viral di kalangan Gen-Z Indonesia.',
                'language'       => 'Indonesian',
                'published_date' => '2021-01-01',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-602-291-016-9',
                'title'          => 'Filosofi Teras',
                'author'         => 'Henry Manampiring',
                'publisher'      => 'Kompas',
                'image'          => 'images/books/filosofi_cover.jpg',
                'shelf_number'   => 'F6-003',
                'category'       => 'Self-Help',
                'stock'          => 18,
                'is_featured'    => true,
                'description'    => 'Penerapan filsafat Stoisisme kuno yang relevan untuk mengatasi kekhawatiran dan melatih ketenangan mental masa kini. Buku self-help terlaris di Indonesia.',
                'language'       => 'Indonesian',
                'published_date' => '2018-11-26',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-979-077-852-2',
                'title'          => 'Madilog',
                'author'         => 'Tan Malaka',
                'publisher'      => 'LPJK',
                'image'          => 'images/books/madilog_real_g.jpg',
                'shelf_number'   => 'G7-001',
                'category'       => 'Philosophy',
                'stock'          => 12,
                'is_featured'    => true,
                'description'    => 'Singkatan dari Materialisme, Dialektika, dan Logika — karya monumental Tan Malaka tentang cara berpikir ilmiah dan kritis yang kembali viral di kalangan anak muda Indonesia.',
                'language'       => 'Indonesian',
                'published_date' => '1943-01-01',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-602-061-362-1',
                'title'          => 'Dear Nathan',
                'author'         => 'Erisca Febriani',
                'publisher'      => 'Best Media',
                'image'          => 'images/books/dear_nathan_wiki.jpg',
                'shelf_number'   => 'B2-011',
                'category'       => 'Romance',
                'stock'          => 22,
                'is_featured'    => true,
                'description'    => 'Novel romance remaja tentang Salma dan Nathan yang viral dari Wattpad dan menjadi fenomena sastra anak muda Indonesia hingga diadaptasi ke film.',
                'language'       => 'Indonesian',
                'published_date' => '2016-01-01',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-602-03-3017-5',
                'title'          => 'Perahu Kertas',
                'author'         => 'Dee Lestari',
                'publisher'      => 'Bentang Pustaka',
                'image'          => 'images/books/perahu_cover.jpg',
                'shelf_number'   => 'B2-012',
                'category'       => 'Fiction',
                'stock'          => 20,
                'is_featured'    => true,
                'description'    => 'Novel tentang Kugy dan Keenan, dua insan yang bermimpi besar dan jatuh cinta. Karya ikonik Dee Lestari yang menjadi simbol generasi kreatif Indonesia.',
                'language'       => 'Indonesian',
                'published_date' => '2009-08-29',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-0-525-55360-5',
                'title'          => 'The Midnight Library',
                'author'         => 'Matt Haig',
                'publisher'      => 'Canongate Books',
                'image'          => 'images/books/midnight_real_g.jpg',
                'shelf_number'   => 'A1-010',
                'category'       => 'Fiction',
                'stock'          => 17,
                'is_featured'    => true,
                'description'    => 'Novel tentang Nora Seed yang menemukan perpustakaan ajaib di antara hidup dan mati, berisi kehidupan-kehidupan yang belum pernah ia jalani. Viral di TikTok BookTok.',
                'language'       => 'English',
                'published_date' => '2020-08-13',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-602-229-446-7',
                'title'          => 'Sirkus Pohon',
                'author'         => 'Andrea Hirata',
                'publisher'      => 'Bentang Pustaka',
                'image'          => 'images/books/sirkus_front_flat.jpg',
                'shelf_number'   => 'B2-013',
                'category'       => 'Fiction',
                'stock'          => 14,
                'is_featured'    => true,
                'description'    => 'Novel penuh warna tentang kehidupan di kampung Melayu, mimpi, cinta, dan pohon filicium yang menjadi saksi segalanya. Karya terbaru Andrea Hirata.',
                'language'       => 'Indonesian',
                'published_date' => '2017-08-17',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-602-04-5446-8',
                'title'          => 'Negeri 5 Menara',
                'author'         => 'A. Fuadi',
                'publisher'      => 'Gramedia Pustaka Utama',
                'image'          => 'images/books/negeri5_real_g.jpg',
                'shelf_number'   => 'B2-014',
                'category'       => 'Fiction',
                'stock'          => 16,
                'is_featured'    => true,
                'description'    => 'Kisah inspiratif tentang Alif dan teman-temannya di Pesantren Madani dengan mantera "Man Jadda Wajada" yang memotivasi jutaan anak muda Indonesia.',
                'language'       => 'Indonesian',
                'published_date' => '2009-07-01',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-602-06-1524-3',
                'title'          => 'Cantik Itu Luka',
                'author'         => 'Eka Kurniawan',
                'publisher'      => 'Gramedia Pustaka Utama',
                'image'          => 'images/books/cantik_itu_luka.jpg',
                'shelf_number'   => 'G7-002',
                'category'       => 'Fiction',
                'stock'          => 13,
                'is_featured'    => false,
                'description'    => 'Novel epik yang mengikuti empat generasi keluarga Dewi Ayu, pelacur cantik yang bangkit dari kuburnya. Karya masterpiece Eka Kurniawan yang diakui dunia internasional.',
                'language'       => 'Indonesian',
                'published_date' => '2002-01-01',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],

            // ─── KOLEKSI KLASIK ───

            [
                'isbn'           => '978-0-7475-3269-9',
                'title'          => 'Harry Potter and the Philosopher\'s Stone',
                'author'         => 'J.K. Rowling',
                'publisher'      => 'Bloomsbury',
                'image'          => 'images/books/hp_cover.jpg',
                'shelf_number'   => 'A1-001',
                'category'       => 'Fantasy',
                'stock'          => 10,
                'is_featured'    => false,
                'description'    => 'Buku pertama seri Harry Potter yang mengisahkan petualangan penyihir muda di sekolah sihir Hogwarts.',
                'language'       => 'English',
                'published_date' => '1997-06-26',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-0-06-112008-4',
                'title'          => 'To Kill a Mockingbird',
                'author'         => 'Harper Lee',
                'publisher'      => 'HarperCollins',
                'image'          => 'images/books/mockingbird_cover.jpg',
                'shelf_number'   => 'B2-002',
                'category'       => 'Fiction',
                'stock'          => 8,
                'is_featured'    => false,
                'description'    => 'Kisah klasik pemenang Hadiah Pulitzer mengenai keadilan rasial dan kepolosan masa kanak-kanak di Amerika Selatan.',
                'language'       => 'English',
                'published_date' => '1960-07-11',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-0-451-52493-5',
                'title'          => '1984',
                'author'         => 'George Orwell',
                'publisher'      => 'Secker & Warburg',
                'image'          => 'images/books/orwell_cover.jpg',
                'shelf_number'   => 'C3-003',
                'category'       => 'Dystopian',
                'stock'          => 12,
                'is_featured'    => false,
                'description'    => 'Novel distopia peringatan tentang totaliterisme, pengawasan massal Big Brother, dan manipulasi kebenaran.',
                'language'       => 'English',
                'published_date' => '1949-06-08',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-0-7352-1129-2',
                'title'          => 'Atomic Habits',
                'author'         => 'James Clear',
                'publisher'      => 'Avery',
                'image'          => 'images/books/atomic_cover.jpg',
                'shelf_number'   => 'F6-001',
                'category'       => 'Self-Help',
                'stock'          => 20,
                'is_featured'    => false,
                'description'    => 'Panduan praktis terbukti membangun kebiasaan baik dan menghilangkan kebiasaan buruk melalui perubahan 1% setiap hari.',
                'language'       => 'English',
                'published_date' => '2018-10-16',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-979-3062-79-2',
                'title'          => 'Laskar Pelangi',
                'author'         => 'Andrea Hirata',
                'publisher'      => 'Bentang Pustaka',
                'image'          => 'images/books/laskar_cover.jpg',
                'shelf_number'   => 'B2-005',
                'category'       => 'Fiction',
                'stock'          => 14,
                'is_featured'    => false,
                'description'    => 'Kisah perjuangan 10 anak di Belitung dalam mengejar pendidikan dan mimpi besar mereka.',
                'language'       => 'Indonesian',
                'published_date' => '2005-01-01',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
            [
                'isbn'           => '978-0-261-10221-7',
                'title'          => 'The Hobbit',
                'author'         => 'J.R.R. Tolkien',
                'publisher'      => 'George Allen & Unwin',
                'image'          => 'images/books/hobbit_cover.jpg',
                'shelf_number'   => 'A1-002',
                'category'       => 'Fantasy',
                'stock'          => 7,
                'is_featured'    => false,
                'description'    => 'Petualangan fantasi epik Bilbo Baggins bersama para kurcaci untuk merebut kembali kerajaan Erebor yang hilang.',
                'language'       => 'English',
                'published_date' => '1937-09-21',
                'created_at'     => now(),
                'updated_at'     => now(),
            ],
        ]);
    }
}