<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BooksSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('books')->insert([
            [
                'isbn' => '978-0-7475-3269-9',
                'title' => 'Harry Potter and the Philosopher\'s Stone',
                'author' => 'J.K. Rowling',
                'publisher' => 'Bloomsbury',
                'image' => 'https://upload.wikimedia.org/wikipedia/en/6/6b/Harry_Potter_and_the_Philosopher%27s_Stone_Book_Cover.jpg',
                'shelf_number' => 'A1-001',
                'category' => 'Fantasy',
                'stock' => 10,
                'description' => 'The first book in the Harry Potter series, following the young wizard Harry Potter.',
                'language' => 'English',
                'published_date' => '1997-06-26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '978-0-06-112008-4',
                'title' => 'To Kill a Mockingbird',
                'author' => 'Harper Lee',
                'publisher' => 'HarperCollins',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/4/4f/To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg',
                'shelf_number' => 'B2-002',
                'category' => 'Fiction',
                'stock' => 8,
                'description' => 'A novel about racial injustice and childhood innocence in the American South.',
                'language' => 'English',
                'published_date' => '1960-07-11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '978-0-14-044913-6',
                'title' => 'Pride and Prejudice',
                'author' => 'Jane Austen',
                'publisher' => 'Penguin Classics',
                'image' => 'https://upload.wikimedia.org/wikipedia/commons/1/17/PrideAndPrejudiceTitlePage.jpg',
                'shelf_number' => 'D4-004',
                'category' => 'Romance',
                'stock' => 15,
                'description' => 'A romantic novel about manners, upbringing, morality, education, and marriage.',
                'language' => 'English',
                'published_date' => '1813-01-28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '978-0-7432-7356-5',
                'title' => 'The Great Gatsby',
                'author' => 'F. Scott Fitzgerald',
                'publisher' => 'Scribner',
                'image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1490528560l/4671.jpg',
                'shelf_number' => 'E5-005',
                'category' => 'Fiction',
                'stock' => 9,
                'description' => 'A novel about the American Dream and the Jazz Age.',
                'language' => 'English',
                'published_date' => '1925-04-10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // --- BUKU TAMBAHAN ---
            [
                'isbn' => '978-0-451-52493-5',
                'title' => '1984',
                'author' => 'George Orwell',
                'publisher' => 'Secker & Warburg',
                'image' => 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1657781256l/61439040.jpg',
                'shelf_number' => 'C3-003',
                'category' => 'Dystopian',
                'stock' => 12,
                'description' => 'A dystopian social science fiction novel and cautionary tale about totalitarianism.',
                'language' => 'English',
                'published_date' => '1949-06-08',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '978-0-261-10221-7',
                'title' => 'The Hobbit',
                'author' => 'J.R.R. Tolkien',
                'publisher' => 'George Allen & Unwin',
                'image' => 'https://upload.wikimedia.org/wikipedia/en/4/4a/TheHobbit_FirstEdition.jpg',
                'shelf_number' => 'A1-002',
                'category' => 'Fantasy',
                'stock' => 7,
                'description' => 'The adventures of Bilbo Baggins as he journeys to reclaim the lost Hobbit Kingdom of Erebor.',
                'language' => 'English',
                'published_date' => '1937-09-21',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '978-0-7352-1129-2',
                'title' => 'Atomic Habits',
                'author' => 'James Clear',
                'publisher' => 'Avery',
                'image' => 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&auto=format&fit=crop',
                'shelf_number' => 'F6-001',
                'category' => 'Self-Help',
                'stock' => 20,
                'description' => 'An easy and proven way to build good habits and break bad ones.',
                'language' => 'English',
                'published_date' => '2018-10-16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '978-979-3062-79-2',
                'title' => 'Laskar Pelangi',
                'author' => 'Andrea Hirata',
                'publisher' => 'Bentang Pustaka',
                'image' => 'https://upload.wikimedia.org/wikipedia/id/8/8e/Laskar_pelangi_sampul.jpg',
                'shelf_number' => 'B2-005',
                'category' => 'Fiction',
                'stock' => 14,
                'description' => 'Kisah perjuangan 10 anak di Belitung dalam mengejar pendidikan.',
                'language' => 'Indonesian',
                'published_date' => '2005-01-01',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '978-602-03-3295-7',
                'title' => 'Bumi',
                'author' => 'Tere Liye',
                'publisher' => 'Gramedia Pustaka Utama',
                'image' => 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=500&auto=format&fit=crop',
                'shelf_number' => 'A1-005',
                'category' => 'Fantasy',
                'stock' => 11,
                'description' => 'Petualangan Raib dan teman-temannya di dunia paralel.',
                'language' => 'Indonesian',
                'published_date' => '2014-01-16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'isbn' => '978-602-291-016-9',
                'title' => 'Filosofi Teras',
                'author' => 'Henry Manampiring',
                'publisher' => 'Kompas',
                'image' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=500&auto=format&fit=crop',
                'shelf_number' => 'F6-003',
                'category' => 'Self-Help',
                'stock' => 18,
                'description' => 'Penerapan filsafat Stoisisme dalam kehidupan sehari-hari untuk mental yang lebih tangguh.',
                'language' => 'Indonesian',
                'published_date' => '2018-11-26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}